### ISSUE TITLE
Light FIXME not displayed

### ISSUE THREAD

**Issue by dfa** [OpenSeaMap/renderer#1]
###### Description
On the fullscreen map the string *please fix position* is disappeared. Wrong placed lights have to be marked. This is necessary for nautical safety.

###### Expected result
* The hint *please fix position* is displayed on unreviewed lights.

#### Migrated from SourceForge

ID: 3597061
Submitted: Markus - 2012-12-17 16:08:28 PST
Details:

On the fullscreen map the string "please fix position" is disappeared. Wrong placed lights has to be marked. This is necessary for nautical security.

**Comment by Nautic** [comment]
Uff - did not remark this closing without solution before... 
A nautical chart with known but not marked errors is a mess :-(
We need a fast solution now!

**Comment by malcolmh** [comment]
Now passed into history!
