### ISSUE TITLE
Slightly better documentation

### ISSUE THREAD

**Issue by pconnell99** [OpenSeaMap/renderer#6]
I'm looking to use the renderer in a commercial project to serve seamap tiles - is there any documentation as to it's use?

**Comment by malcolmh** [comment]
Unfortunately not. The basic renderer "searender" generates a Normal Mercator projected SVG file from an OSM file. Exactly how you use it is dependant on your intended tile server environment.

**Comment by CptLeeChuck** [comment]
I try to bulk generate OpenSeaMap tiles with this renderer to use my own tileserver to relieve tiles/t1.openseamap.org, unfortunately without success so far. 
I was able to manually render a single SVG file with this command:
```
./searender ./symbols/symbols.defs 18 45.4342791127,13.5177986622,45.4347420941,13.5185153484 >tmp/UmagMoleLight.svg <tmp/myCroatiaSubpartHarborUmag.osm
```
But I’m not able to automate tile generation so far.

As I understood I need to execute ./tilegen however ./tilegen seems to need the *.OSM input files already with tiles-coordinates in the filename.
How can I prepare those best? And what is jtile.jar in line 43 and where to get it?

Or do I need to execute ./rerender? Which looks to me as it would prepare OSM files accordingly with osmosis. But it also seems to process only zoom level 9 – 12? And I don’t know what kind of input I need to prepare for it.

Could you please point me in the right direction how to generate all OpenSeaMap tiles (named with the correct coordinates) for a defined area (e.g. Istria/Croatia) for all zoom levels?

**Comment by malcolmh** [comment]
If you want to generate the same tiles as are found on t1.openseamap.org, then you can use my scripts "render" & "tilegen". These scripts call the Java programs "Jsearch" & "Jtile". To build Jsearch & Jtile, both JDK and Apache Ant are needed, as well as the Apache Batik library.

The input is an extract from the planet DB of all objects with a "seamark:type" tag. The scripts are run from the directory "work", where there should be sub-directories "tmp" & "tiles". You will note that "render" waits for the appearance of a file "done" which indicates that a file "next.osm" has been generated.

**Comment by stevo01** [comment]
Hallo Malcolm,
I had a closer look into your scripts today and now some questions for realization of a "t1.openseamap.org" clone:
- is the world.osm and next.osm really an osm extract of the whole world? 
- what are the recommenced hardware requirements (number of CPU cores, RAM and disk space) and whats the estimated runtime for rendering of all tiles?

Best Regards

Steffen

**Comment by malcolmh** [comment]
This renderer is now obsolete. The replacement has been running for several months and uploading to t1.openseamap.org. You can find the code here: https://github.com/OpenNauticalChart/renderer. I will close this issue and re-open it in the the new location.
