### ISSUE TITLE
searender segmentation faults

### ISSUE THREAD

**Issue by praabjerg** [OpenSeaMap/renderer#8]
Hey! I am currently working on a project where we want to render a world-wide map layer with at least some of the SeaMark symbols. For this reason, I have been playing around with the rendering scripts.
They seem to work most of the time, but occasionally, searender will throw a segmentation fault on one of the *.osm tiles generated by jsearch, causing an incomplete *.svg to be generated, which then of course causes batik to throw TranscoderExceptions in jtile.
The end result is that some of the *.png tiles end up missing after the final step.

I am not sure if this is a local problem with a C library on my computer, or if it even happens on the OpenSeaMap tile server. But it could potentially explain why I sometimes see areas with obviously missing tiles from the public servers, like:
http://map.openseamap.org/?zoom=13&lat=59.62631&lon=20.30568&layers=BFTFFFFFFFF0FFFFFFFFFF
or
http://map.openseamap.org/?zoom=14&lat=1.4807&lon=102.99102&layers=BFTFFFFFFFF0FFFFFFFFFF

The fact that the missing areas are the same from zoom level 12 and down is consistent with my issue, and the way the rendering pipeline works. Pngs for the higher zoom levels are generated from the level 12 svgs, so when one of those end up incomplete because of a segfault, all the pngs for that area from zoom level 12 and up disappear.

I am attaching a zip file with a set of *.osm tiles (generated by jsearch) that my local instance of searender consistently segfaults on. They originate from a local extract I populated my database with, using the service on http://download.bbbike.org/osm/ , covering Copenhagen and Malmö.

Unless this is just a local problem with one of my C libraries, then running, for example,
./searender symbols/symbols.defs 12 >2195-1282-12.svg <2195-1282-12.osm
will cause the segfault.

Unfortunately, I am not familiar enough with the searender code to localise the problem right away, but if you're having the same problem on the public OpenSeaMap tile servers, hopefully this will be of some help.
[OSMsThatWillSegfaultSeaRender.zip](https://github.com/OpenSeaMap/renderer/files/81201/OSMsThatWillSegfaultSeaRender.zip)

**Comment by praabjerg** [comment]
So, my C is a bit rusty, but with the help of gdb, I think I found what is causing the issue.
It is the call to strtok on line 1077 in render.c:
```
int drawText(Item_t *item, char *text, char *style, double dx, double dy) {
  XY_t coord = findCentroid(item);
  if ((coord.x > 0.0) || (coord.y > 0.0)) {
    printf("<text id=\"%d\" ", ++ref);
    double size = scaleStyle(style) * 1.1;
    double x = coord.x + (dx*symbolScale[zoom]);
    double y = coord.y + (dy*symbolScale[zoom]);
    char *line = strtok(text, "\n");
    double dy = 0.0;
    printf("y=\"%f\">", y);
    while (line != NULL) {
      printf("<tspan x=\"%f\" dy=\"%f\">%s</tspan>\n", x, dy, line);
      dy = size;
      line = strtok(NULL, "\n");
    }
    printf("</text>\n");
    return ref;
  }
  return 0;
}
```
That call will sometimes receive a string literal in the text parameter, which will cause a segmentation fault because strtok then attempts to modify a string literal. In my case, gdb identified line 724 and 469 in rules.c as entry points (receiving the literals "(Shoal)" and "V-AIS" respectively).

**Comment by malcolmh** [comment]
There must be a difference in our run time environments as I do not get seg. faults when I run searender with the OSMs that you specify. Also the "missing tiles" that you refer to are in fact non-rendering of areas where there is no nodes within the 3x3 zoom-12 tile window I use. That problem is cured by adding nodes to very long ways (5 NM spacing is usually sufficient for most latitudes).

I have modified "drawtext" to make it safe when used with literal strings. Please try that.

**Comment by praabjerg** [comment]
How odd. Well, the modification works. I can now render the tiles without any errors on my local environment as well.
Thanks!
